export type Locale = 'en' | 'ja'

export const dictionaries = {
    en: {
        hero: {
            title: 'Premier AI Audio Assets for Creators',
            description: 'High-quality, royalty-free audio tracks generated by advanced AI. Perfect for games, videos, and streaming.',
            getStarted: 'Get Started',
            browseLibrary: 'Browse Library',
            twitterFollow: 'Follow along on X',
            loggedIn: 'Logged In',
        },
        notifications: {
            title: 'Notifications',
            empty: 'No new notifications.',
            markRead: 'Mark all as read',
            items: [
                {
                    id: '1',
                    date: '2026-02-10',
                    content: 'Welcome to Zalci Audio! Explore our new collection of AI-generated sounds.'
                },
                {
                    id: '2',
                    date: '2026-02-09',
                    content: 'Maintenance scheduled for Feb 15th, 2026 (02:00 - 04:00 UTC).'
                }
            ]
        },
        header: {
            title: 'Zalci Audio',
            sounds: 'Sounds',
            pricing: 'Pricing',
            about: 'About',
            terms: 'Terms of Service',
            legal: 'Legal',
            login: 'Login',
            signOut: 'Sign Out',
            getStarted: 'Get Started',
            searchPlaceholder: 'Search songs...',
            myLibrary: 'My Library',
            library: 'Library',
            myPage: 'My Page',
        },
        featured: {
            title: 'Featured Tracks',
            description: 'Discover our latest AI-generated masterpieces. High-quality audio tracks ready for your next project.',
        },
        empty: 'No songs available at the moment.',
        card: {
            buyNow: 'Buy Now',
            processing: 'Processing...',
            error: 'Something went wrong. Please try again.',
        },
        sounds: {
            title: 'All Sounds',
            description: 'Explore our complete collection of high-quality audio assets.',
            empty: 'No songs available yet.',
            failed: 'Failed to load sounds. Please try again later.',
            sort: {
                label: 'Sort by',
                latest: 'Latest',
                oldest: 'Oldest',
                priceHigh: 'Price: High to Low',
                priceLow: 'Price: Low to High',
                nameAsc: 'Name: A-Z',
                nameDesc: 'Name: Z-A',
            }
        },
        library: {
            title: 'My Library',
            description: 'Manage and download your purchased sounds.',
            signInTitle: 'Sign in to view your library',
            signInDesc: 'You need to be logged in to access your purchased content.',
            signInButton: 'Sign In / Sign Up',
            emptyTitle: 'Your library is empty',
            emptyDesc: "You haven't purchased any sounds yet. Browse our collection to find the perfect audio for your project.",
            browseButton: 'Browse Sounds',
            purchasedPrefix: 'Purchased on',
        },
        about: {
            title: 'About Zalci Audio',
            description: 'Unleash the sound within.',
            missionTitle: 'Our Mission',
            missionDesc: 'Zalci Audio is dedicated to providing high-quality, game-ready audio assets for developers and creators. We believe that sound is 50% of the experience, and our goal is to help you elevate your projects with professional-grade sound effects and music.',
            creatorTitle: 'The Creator',
            creatorDesc: 'With years of experience in game development and sound design, we understand the specific needs of indie developers and studios. Every asset in our store is crafted with attention to detail and usability in mind.',
            contactTitle: 'Contact',
            contactDesc: 'Have questions or custom requests? Reach out to us directly through our social media channels or check back later for a contact form.',
        },
        purchaseModal: {
            preview: 'Preview (20s Sample)',
            playSample: 'Play Sample',
            pause: 'Pause',
            purchaseOptions: 'Purchase Options',
            totalAmount: 'Total Amount',
            payWithStripe: 'Pay with Stripe',
            processing: 'Processing...',
            securedBy: 'Secure checkout powered by Stripe',
            options: {
                wav: 'WAV Format (High Quality)',
                loop: 'Loop Version Included',
                highRes: 'High-Res Audio (96kHz/24bit)',
                midi: 'MIDI Data',
            }
        },
        login: {
            signInTitle: 'Sign In',
            signUpTitle: 'Create Account',
            emailLabel: 'Email',
            passwordLabel: 'Password',
            signInButton: 'Sign In',
            signUpButton: 'Sign Up',
            toggleToSignUp: "Don't have an account? Sign Up",
            toggleToSignIn: 'Already have an account? Sign In',
            loading: 'Loading...',
            successTitle: 'Check your email',
            successDesc: 'We sent you a login link.',
            errorTitle: 'Authentication Error',
            loggedIn: 'Logged In',
        },
        terms: {
            title: 'Terms of Service',
            sections: [
                {
                    title: '1. Introduction',
                    content: 'These Terms of Service govern your use of Zalci Audio. By accessing or using our service, you agree to be bound by these terms.'
                },
                {
                    title: '2. License to Use',
                    content: 'When you purchase an audio asset from Zalci Audio, you are granted a non-exclusive, royalty-free license to use the asset in your personal or commercial projects, including games, videos, and streams. You may not resell or redistribute the assets as standalone files.'
                },
                {
                    title: '3. User Accounts',
                    content: 'To access certain features, you may need to create an account. You are responsible for maintaining the confidentiality of your account information.'
                },
                {
                    title: '4. Purchases and Refunds',
                    content: 'All sales are final. Due to the digital nature of our products, we do not generally offer refunds unless the file is defective.'
                },
                {
                    title: '5. Prohibited Uses',
                    content: 'You may not use our assets for any illegal purpose or in a way that violates the rights of others.'
                },
                {
                    title: '6. Changes to Terms',
                    content: 'We reserve the right to modify these terms at any time. Continued use of the service constitutes acceptance of the new terms.'
                }
            ]
        }
    },
    ja: {
        hero: {
            title: 'クリエイターのための最高級AIオーディオ資産',
            description: '高度なAIによって生成された高品質でロイヤリティフリーのオーディオトラック。ゲーム、動画、ストリーミングに最適です。',
            getStarted: '始める',
            browseLibrary: 'ライブラリを見る',
            twitterFollow: 'Xでフォローする',
            loggedIn: 'ログイン済み',
        },
        notifications: {
            title: 'お知らせ',
            empty: '新しいお知らせはありません。',
            markRead: 'すべて既読にする',
            items: [
                {
                    id: '1',
                    date: '2026/02/10',
                    content: 'Zalci Audioへようこそ！新着のAI生成サウンドをぜひチェックしてください。'
                },
                {
                    id: '2',
                    date: '2026/02/09',
                    content: '2026年2月15日 (02:00 - 04:00 UTC) にシステムメンテナンスを実施予定です。'
                }
            ]
        },
        header: {
            title: 'Zalci Audio',
            sounds: 'サウンド',
            pricing: '料金',
            about: '概要',
            terms: '利用規約',
            legal: '特定商取引法',
            login: 'ログイン',
            signOut: 'ログアウト',
            getStarted: '始める',
            searchPlaceholder: '楽曲を検索...',
            myLibrary: 'マイライブラリ',
            library: 'ライブラリ',
            myPage: 'マイページ',
        },
        featured: {
            title: '注目トラック',
            description: '最新のAI生成傑作をご覧ください。あなたの次のプロジェクトのための高品質なオーディオトラックです。',
        },
        empty: '現在利用可能な楽曲はありません。',
        card: {
            buyNow: '購入する',
            processing: '処理中...',
            error: 'エラーが発生しました。もう一度お試しください。',
        },
        sounds: {
            title: '全サウンド一覧',
            description: '高品質なオーディオアセットの全コレクションをご覧ください。',
            empty: 'まだ楽曲がありません。',
            failed: '曲の読み込みに失敗しました。後でもう一度お試しください。',
            sort: {
                label: '並び替え',
                latest: '新着順',
                oldest: '古い順',
                priceHigh: '価格が高い順',
                priceLow: '価格が安い順',
                nameAsc: '名前順 (A → Z)',
                nameDesc: '名前順 (Z → A)',
            }
        },
        library: {
            title: 'マイライブラリ',
            description: '購入したサウンドの管理とダウンロードができます。',
            signInTitle: 'ライブラリを表示するにはサインイン',
            signInDesc: '購入したコンテンツにアクセスするにはログインが必要です。',
            signInButton: 'サインイン / 新規登録',
            emptyTitle: 'ライブラリは空です',
            emptyDesc: "まだサウンドを購入していません。コレクションを見て、プロジェクトに最適なオーディオを見つけましょう。",
            browseButton: 'サウンドを探す',
            purchasedPrefix: '購入日:',
        },
        about: {
            title: 'Zalci Audioについて',
            description: '内なる響きを解き放て。',
            missionTitle: '私たちのミッション',
            missionDesc: 'Zalci Audioは、開発者やクリエイターに高品質でゲーム対応のオーディオアセットを提供することに専念しています。私たちはサウンドが体験の50%を占めると信じており、プロフェッショナルな効果音と音楽であなたのプロジェクトを向上させるお手伝いをすることが目標です。',
            creatorTitle: 'クリエイターについて',
            creatorDesc: 'ゲーム開発とサウンドデザインにおける長年の経験を活かし、インディー開発者やスタジオの具体的なニーズを理解しています。ストア内のすべてのアセットは、細部へのこだわりと使いやすさを考慮して作られています。',
            contactTitle: 'お知らせ・お問い合わせ',
            contactDesc: 'ご質問やリクエストは、SNS等で直接お問い合わせいただくか、後日設置されるコンタクトフォームをご確認ください。',
        },
        purchaseModal: {
            preview: 'プレビュー (20秒サンプル)',
            playSample: 'サンプル再生',
            pause: '一時停止',
            purchaseOptions: '購入オプション',
            totalAmount: '合計金額',
            payWithStripe: 'Stripeで支払う',
            processing: '処理中...',
            securedBy: 'Stripeによる安全な決済',
            options: {
                wav: 'WAV形式 (高音質)',
                loop: 'ループバージョンを含む',
                highRes: 'ハイレゾ音源 (96kHz/24bit)',
                midi: 'MIDIデータ',
            }
        },
        login: {
            signInTitle: 'サインイン',
            signUpTitle: 'アカウント作成',
            emailLabel: 'メールアドレス',
            passwordLabel: 'パスワード',
            signInButton: 'サインイン',
            signUpButton: '登録する',
            toggleToSignUp: 'アカウントをお持ちでないですか？ 新規登録',
            toggleToSignIn: 'すでにアカウントをお持ちですか？ サインイン',
            loading: '処理中...',
            successTitle: 'メールを確認してください',
            successDesc: 'ログインリンクを送信しました。',
            errorTitle: '認証エラー',
            loggedIn: 'ログイン済み',
        },
        terms: {
            title: '利用規約',
            sections: [
                {
                    title: '第1条（適用）',
                    content: '本利用規約（以下「本規約」といいます）は、Zalci Audio（以下「当サイト」といいます）が提供するオーディオ素材販売サービス（以下「本サービス」といいます）の利用条件を定めるものです。ユーザーは、本サービスの利用をもって本規約のすべての条項に同意したものとみなします。'
                },
                {
                    title: '第2条（使用許諾および権利の帰属）',
                    content: '権利の帰属: 本サービスで販売・配布される全てのオーディオ素材（以下「素材」といいます）の著作権および著作者人格権は、当サイトまたは当サイトに素材を提供したクリエイターに帰属します。本規約は、ユーザーに対して素材の著作権を譲渡するものではありません。\n\n許諾範囲: 当サイトはユーザーに対し、以下の条件に基づく非独占的かつ再許諾不可能な使用権を許諾します。\n\n用途: ゲーム、動画、配信、アプリケーション、ウェブサイト等のデジタルコンテンツ、および映像作品等の制作物（以下「成果物」といいます）への組み込み。商用・非商用を問いません。\n\n加工: ユーザーは、成果物の制作に必要な範囲で、素材のトリミング、ループ処理、音質調整等の改変を行うことができます。\n\nクレジット表記: 成果物へのクレジット表記（例：「Sound: Zalci Audio」等）は任意としますが、表記を推奨します。'
                },
                {
                    title: '第3条（禁止事項）',
                    content: 'ユーザーは、本サービスの利用にあたり、以下の行為を行ってはなりません。\n\n再配布・転売: 素材そのもの、または素材に軽微な加工を加えただけのものを、独立したファイルとして第三者に再配布、転売、貸与、譲渡する行為（BGM集としての販売、素材販売サイトへの登録等を含みます）。\n\n著作権管理システムへの登録: 素材、または素材を使用した成果物を、YouTube Content ID、JASRAC等の著作権管理団体、またはこれらに類する著作権管理システム・データベースに登録する行為。\n\nAI学習への利用: 素材を生成系AI（人工知能）の学習用データとして利用する行為、および素材を利用して生成系AIにより類似の音声を意図的に生成する行為。\n\n不正利用: 公序良俗に反する目的、犯罪行為、反社会的勢力に関連する活動、または他者の権利を侵害する目的で素材を利用する行為。\n\nアカウントの共有: 1つのアカウントを複数人で共有する行為、またはアカウント情報を第三者に譲渡・貸与する行為。'
                },
                {
                    title: '第4条（返品・キャンセル・再ダウンロード）',
                    content: '返品不可: デジタルコンテンツという商品の性質上、購入手続き完了後のキャンセル、返品、返金は原則としてお受けできません。\n\n欠陥時の対応: ダウンロードされたファイルに破損等の技術的な欠陥が認められた場合に限り、当サイトの判断により、良品との交換または再ダウンロードの措置を講じます。ただし、ユーザーの利用環境（ソフトウェア、ハードウェアの非互換性等）に起因する不具合については対象外とします。'
                },
                {
                    title: '第5条（免責事項）',
                    content: '非保証: 当サイトは、素材の完全性、正確性、特定の目的への適合性、および第三者の権利侵害の有無について、明示または黙示を問わず何ら保証しません。\n\n損害の免責: 本サービスの利用、または利用不能によりユーザーに生じたあらゆる損害（データの消失、業務の中断、逸失利益、精神的苦痛等を含みますがこれらに限定されません）について、当サイトは一切の責任を負いません。\n\nトラブルの解決: ユーザーが本サービスを利用したことにより第三者との間で生じた紛争（著作権侵害の申立て等を含みます）については、ユーザーの責任と費用において解決するものとし、当サイトは関与しません。'
                },
                {
                    title: '第6条（規約の変更）',
                    content: '当サイトは、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。変更後の規約は、当サイト上に掲示した時点で効力を生じるものとし、以降の利用については変更後の規約が適用されます。'
                },
                {
                    title: '第7条（通知および連絡）',
                    content: 'デジタルファースト: 本サービスに関する当サイトからユーザーへの通知、およびユーザーから当サイトへの連絡は、原則として電子メール、または当サイト内の問い合わせフォームを通じて行うものとします。\n\n郵送物の受領: 当サイトの運営体制およびセキュリティ保持の観点から、事前の承諾なく送付された書面（郵便物、宅配便等）について、当サイトは受領の義務を負わず、これによってユーザーに生じた不利益について一切の責任を負いません。'
                },
                {
                    title: '第8条（準拠法・裁判管轄）',
                    content: '準拠法: 本規約の解釈にあたっては、日本法を準拠法とします。\n\n管轄裁判所: 本サービスに関して紛争が生じた場合には、当サイト運営者の所在地を管轄する地方裁判所を第一審の専属的合意管轄裁判所とします。'
                }
            ]
        }
    },
}
