export type Locale = 'en' | 'ja'

export const dictionaries = {
    en: {
        hero: {
            title: 'Premier AI Audio Assets\nfor Creators',
            description: 'High-quality, royalty-free audio tracks generated by advanced AI.\nPerfect for games, videos, and streaming.',
            getStarted: 'Get Started',
            browseLibrary: 'Browse Library',
            twitterShare: 'Share on X',
            loggedIn: 'Logged In',
        },
        notifications: {
            title: 'Notifications',
            empty: 'No new notifications.',
            markRead: 'Mark all as read',
            items: [
                {
                    id: '1',
                    date: '2026-02-10',
                    content: 'Welcome to Zalci Audio! Explore our new collection of AI-generated sounds.'
                },
                {
                    id: '2',
                    date: '2026-02-09',
                    content: 'Maintenance scheduled for Feb 15th, 2026 (02:00 - 04:00 UTC).'
                }
            ]
        },
        header: {
            title: 'Zalci Audio',
            sounds: 'All Sounds',
            pricing: 'Pricing',
            about: 'About',
            terms: 'Terms of Service',
            privacy: 'Privacy Policy',
            legal: 'Legal',
            login: 'Login',
            signOut: 'Sign Out',
            getStarted: 'Get Started',
            searchPlaceholder: 'Search songs...',
            myLibrary: 'My Library',
            library: 'Library',
            myPage: 'My Page',
        },
        featured: {
            title: 'Featured Tracks',
            description: 'Discover our latest AI-generated masterpieces.\nHigh-quality audio tracks ready for your next project.',
        },
        empty: 'No songs available at the moment.',
        card: {
            buyNow: 'Buy Now',
            processing: 'Processing...',
            error: 'Something went wrong. Please try again.',
            inLibrary: 'In Library',
            free: 'FREE',
            freeDownload: 'Free Download',
        },
        sounds: {
            title: 'All Sounds',
            description: 'Explore our complete collection of high-quality audio assets.',
            empty: 'No songs available yet.',
            failed: 'Failed to load sounds. Please try again later.',
            sort: {
                label: 'Sort by',
                latest: 'Latest',
                oldest: 'Oldest',
                priceHigh: 'Price: High to Low',
                priceLow: 'Price: Low to High',
                nameAsc: 'Name: A-Z',
                nameDesc: 'Name: Z-A',
            }
        },
        library: {
            title: 'My Library',
            description: 'Manage and download your purchased sounds.',
            signInTitle: 'Sign in to view your library',
            signInDesc: 'You need to be logged in to access your purchased content.',
            signInButton: 'Sign In / Sign Up',
            emptyTitle: 'Your library is empty',
            emptyDesc: "You haven't purchased any sounds yet. Browse our collection to find the perfect audio for your project.",
            browseButton: 'Browse Sounds',
            purchasedPrefix: 'Purchased on',
        },
        about: {
            title: 'About Zalci Audio',
            tagline: '"The power of Generative AI, for every creator."\nNo high-spec PC or complex prompts required.',
            conceptTitle: 'About Zalci Audio',
            conceptDesc: '"I want to use high-performance generative AI, but my PC specs aren\'t enough..."\n"It\'s honestly a hassle to repeat generations until I\'m satisfied."\n\nZalci Audio is a store that carefully selects and provides sounds that we believe are "the one" by utilizing the latest AI technology on behalf of such creators.\n\nAll you have to do is find your favorite sound from the library and download it.\nLeave the "tedious parts" of production to us and focus on your creative work.',
            roadmapTitle: 'Current Lineup and Future Expansion',
            roadmapDesc: 'Currently, our store provides materials mainly in the easy-to-handle and lightweight mp3 format.\nHowever, Zalci Audio does not stop here. In the future, we plan to implement the following updates to meet the more advanced needs of creators.\n\n- Addition of high-quality WAV format (for professional production)\n- Seamlessly looped materials (for smoother game implementation)\n- Sale of MIDI data (for those who want to freely customize melodies)\n\nAs a library that continues to grow, we support your project.',
            messageTitle: 'From a Current Game Developer\'s Perspective',
            messageDesc: 'As a student learning game development (Unity/C++), I am shaping the "sounds I wanted now" myself.\nI am aiming to be a material shop that draws out the maximum potential of AI and that developers can use without stress.',
        },
        purchaseModal: {
            preview: 'Preview (20s Sample)',
            playSample: 'Play Sample',
            pause: 'Pause',
            purchaseOptions: 'Purchase Options',
            totalAmount: 'Total Amount',
            payWithStripe: 'Pay with Stripe',
            processing: 'Processing...',
            securedBy: 'Secure checkout powered by Stripe',
            options: {
                wav: 'WAV Format (High Quality)',
                loop: 'Loop Version Included',
                highRes: 'High-Res Audio (96kHz/24bit)',
                midi: 'MIDI Data',
            }
        },
        login: {
            signInTitle: 'Sign In',
            signUpTitle: 'Create Account',
            emailLabel: 'Email Address',
            passwordLabel: 'Password',
            submitButton: 'Login',
            submitButtonSignUp: 'Sign Up',
            loading: 'Processing...',
            forgotPassword: 'Forgot Password?',
            noAccount: "Don't have an account?",
            hasAccount: 'Already have an account?',
            signUpLink: 'Sign Up',
            loginLink: 'Login',
            welcome: '',
            welcomeDesc: 'Enter your credentials to access your account',
            createAccount: 'Create Account',
            createAccountDesc: 'Enter your details to create a new account',
            backToHome: 'Back to Home',
            newsletterLabel: 'I would like to receive updates and promotional emails',
            signUpSuccess: 'Nice to meet you. Registration completed. Please log in.',
            inputComplete: 'Input completed.',
            errors: {
                invalidCredentials: 'Invalid login credentials.',
                userExists: 'User already registered.',
                weakPassword: 'Password should be at least 6 characters.',
                unknown: 'An unexpected error occurred.',
            },
            continueWith: 'Or continue with',
            google: 'Google',
            twitter: 'X',
        },
        forgotPassword: {
            title: 'Reset Password',
            description: 'Enter your email address and we will send you a link to reset your password.',
            emailLabel: 'Email Address',
            submitButton: 'Send Reset Link',
            backToLogin: 'Back to Login',
            successTitle: 'Check your email',
            successDesc: 'If an account exists for that email, we have sent a password reset link.',
            loading: 'Sending...',
            errors: {
                invalidEmail: 'Please enter a valid email address.',
                userNotFound: 'If an account exists, a link has been sent.',
                rateLimit: 'Too many requests. Please try again later.',
                unknown: 'An error occurred. Please try again.',
            }
        },
        updatePassword: {
            title: 'Update Password',
            description: 'Enter your new password below.',
            passwordLabel: 'New Password',
            confirmPasswordLabel: 'Confirm Password',
            submitButton: 'Update Password',
            successTitle: 'Password Updated',
            successDesc: 'Your password has been changed successfully.',
            matchError: 'Passwords do not match.',
            loading: 'Updating...',
            errors: {
                weakPassword: 'Password should be at least 6 characters.',
                sessionExpired: 'Session expired. Please request a new link.',
                unknown: 'An error occurred. Please try again.',
            }
        },
        terms: {
            title: 'Terms of Service',
            sections: [
                {
                    title: 'Article 1 (Applicability)',
                    content: 'These Terms of Service (hereinafter referred to as "Terms") govern the use of the audio asset sales service (hereinafter referred to as the "Service") provided by Zalci Audio (hereinafter referred to as the "Site"). Users are deemed to have agreed to all provisions of these Terms by using the Service.'
                },
                {
                    title: 'Article 2 (License and Attribution of Rights)',
                    content: 'Attribution of Rights: The copyright and moral rights of all audio assets (hereinafter referred to as "Assets") sold or distributed on this Service belong to this Site or the creators who provided the Assets to this Site. These Terms do not transfer the copyright of the Assets to the user.\n\nScope of License: This Site grants the user a non-exclusive, non-sublicensable right to use the Assets under the following conditions.\n\nUsage: Incorporation into digital content such as games, videos, streams, applications, websites, and productions such as video works (hereinafter referred to as "Deliverables"). Commercial or non-commercial use is permitted.\n\nModification: Users may perform modifications such as trimming, looping, and sound quality adjustment of the Assets to the extent necessary for the production of Deliverables.\n\nCredit Notation: Credit notation on Deliverables (e.g., "Sound: Zalci Audio") is optional, but recommended.'
                },
                {
                    title: 'Article 3 (Prohibited Acts)',
                    content: 'Users shall not engage in the following acts when using the Service.\n\nRedistribution/Resale: Redistributing, reselling, lending, or transferring the Assets themselves, or Assets with only minor processing, as standalone files to third parties (including selling as BGM collections, registering on asset sales sites, etc.).\n\n著作権管理システムへの登録: 素材、または素材を使用した成果物を、YouTube Content ID、JASRAC等の著作権管理団体、またはこれらに類する著作権管理システム・データベースに登録する行為。\n\nUse for AI Learning: Using Assets as training data for generative AI (artificial intelligence), and intentionally generating similar audio using generative AI using the Assets.\n\nUnauthorized Use: Using Assets for purposes contrary to public order and morals, criminal acts, activities related to anti-social forces, or purposes that infringe on the rights of others.\n\nAccount Sharing: Sharing one account with multiple people, or transferring or lending account information to a third party.'
                },
                {
                    title: 'Article 4 (Returns, Cancellations, and Redownloads)',
                    content: 'No Returns: Due to the nature of digital content products, cancellations, returns, and refunds after the completion of purchase procedures are generally not accepted.\n\nResponse to Defects: Only if technical defects such as corruption are found in the downloaded file, we will take measures to exchange it for a non-defective product or allow redownloading at our discretion. However, defects caused by the user\'s usage environment (software, hardware incompatibility, etc.) are not covered.'
                },
                {
                    title: 'Article 5 (Disclaimer)',
                    content: 'No Warranty: This Site makes no warranty, express or implied, regarding the integrity, accuracy, fitness for a particular purpose of the Assets, or the absence of infringement of third-party rights.\n\nExemption from Damages: This Site shall not be liable for any damages (including but not limited to loss of data, business interruption, lost profits, mental anguish, etc.) incurred by the user due to the use or inability to use the Service.\n\nDispute Resolution: Any disputes arising between the user and a third party due to the use of this Service (including claims of copyright infringement, etc.) shall be resolved at the user\'s responsibility and expense, and this Site shall not be involved.'
                },
                {
                    title: 'Article 6 (Changes to Terms)',
                    content: 'This Site may change these Terms at any time without notifying the user if deemed necessary. The changed Terms shall take effect when posted on this Site, and the changed Terms shall apply to subsequent use.'
                },
                {
                    title: 'Article 7 (Notifications and Communications)',
                    content: 'Digital First: Notifications from this Site to users regarding this Service, and communications from users to this Site, shall generally be made via email or the inquiry form within this Site.\n\nReceipt of Postal Items: From the viewpoint of this Site\'s operation system and security maintenance, this Site assumes no obligation to receive documents (mail, courier, etc.) sent without prior consent, and assumes no responsibility for any disadvantage caused to the user by this.'
                },
                {
                    title: 'Article 8 (Governing Law and Jurisdiction)',
                    content: 'Governing Law: The interpretation of these Terms shall be governed by the laws of Japan.\n\nJurisdiction: In the event of a dispute regarding this Service, the district court having jurisdiction over the location of the operator of this Site shall be the exclusive agreed court of first instance.'
                }
            ]
        },
        policy: {
            title: 'Privacy Policy',
            intro: 'Zalci Audio (hereinafter referred to as "the Site") establishes the following privacy policy (hereinafter referred to as "this Policy") regarding the handling of users\' personal information in the services provided on this website (hereinafter referred to as "the Service").',
            sections: [
                {
                    title: 'Article 1 (Personal Information)',
                    content: '"Personal Information" shall refer to "personal information" as defined in the Personal Information Protection Act, and means information about a living individual that can identify a specific individual by name, date of birth, address, telephone number, contact information, or other descriptions contained in such information, as well as data related to physical characteristics, fingerprints, voiceprints, and information that can identify a specific individual from such information alone, such as the insurer number on a health insurance card (personal identification code).'
                },
                {
                    title: 'Article 2 (Method of Collection)',
                    content: 'The Site may collect the following information when users use the Service.\n\nUser Provided Information: Name, email address, address, phone number, and other information required for account registration and payment.\n\nPayment Information: Credit card information, bank account information (*Credit card information is managed by the payment processing company and is not held by the Site).\n\nAutomatically Collected Information: IP address, cookies, access logs, usage environment (browser, OS, etc.), and access analysis data such as time spent on the site.'
                },
                {
                    title: 'Article 3 (Management and Security)',
                    content: 'Password Protection: The Site collects and maintains the email address and password for the user\'s account. Passwords are saved in an encrypted state using appropriate hashing algorithms (salting, etc.), and we implement strict management so that even the Site operators cannot view or restore the original password.\n\nSecurity Measures: The Site implements SSL (Secure Sockets Layer) encryption for communication and appropriate technical measures to prevent unauthorized access, aiming to prevent leakage, loss, or damage of personal information.\n\nUser Responsibility: Users are responsible for managing their passwords properly so that they are not known to third parties. We strongly recommend avoiding passwords that are easily guessed or reusing passwords from other sites.'
                },
                {
                    title: 'Article 4 (Purpose of Use)',
                    content: 'The purposes for which the Site collects and uses personal information are as follows.\n\nTo provide and operate the Service (sending download links, providing My Page functions, etc.).\n\nTo respond to inquiries from users (including identity verification).\n\nTo bill for usage fees in paid services.\n\nTo contact users as necessary for maintenance, important notices, etc.\n\nTo identify users who violate the Terms of Service or attempt to use the service for fraudulent or unjust purposes, and to refuse their use.\n\nPurposes incidental to the above purposes of use.'
                },
                {
                    title: 'Article 5 (Provision to Third Parties)',
                    content: 'The Site will not provide personal information to third parties without obtaining the user\'s prior consent, except in the following cases, unless permitted by the Personal Information Protection Act or other laws and regulations.\n\nWhen it is necessary for the protection of the life, body, or property of a person and it is difficult to obtain the consent of the person.\n\nWhen it is particularly necessary for improving public health or promoting the sound growth of children and it is difficult to obtain the consent of the person.\n\nWhen it is necessary to cooperate with a national agency, a local government, or an individual or entity entrusted by either in executing affairs prescribed by laws and regulations and obtaining the consent of the person is likely to impede the execution of such affairs.'
                },
                {
                    title: 'Article 6 (Outsourcing and Payment Processing)',
                    content: 'The Site may delegate part of the handling of personal information to external parties (payment processing companies, server management companies, etc.) to the extent necessary for the operation of the Service. In this case, the Site will exercise appropriate supervision, such as concluding a confidentiality agreement with the entrusted party.\n\nCredit Card Payment: We use Stripe, Inc.\'s (Stripe Japan K.K.) payment service for credit card payments in the Service. User\'s credit card information is sent directly to Stripe\'s servers and is not stored on the Site\'s servers or databases at all.'
                },
                {
                    title: 'Article 7 (Access Analysis Tools)',
                    content: 'The Site uses "Google Analytics" by Google for access analysis. Google Analytics uses cookies to collect traffic data. This traffic data is collected anonymously and does not identify individuals. You can refuse collection by disabling cookies, so please check your browser settings.'
                },
                {
                    title: 'Article 8 (Disclosure, Correction, Suspension of Use, etc.)',
                    content: 'When a user requests disclosure, correction, addition, deletion, suspension of use, or elimination (hereinafter referred to as "Disclosure, etc.") of personal information, we will respond without delay after confirming the identity of the person. However, this does not apply if the Site is not obligated to perform Disclosure, etc., under the Personal Information Protection Act or other laws.'
                },
                {
                    title: 'Article 9 (Changes to Privacy Policy)',
                    content: 'The contents of this Policy may be changed without notice to the user, except for matters otherwise provided by law or this Policy. Unless otherwise specified by the Site, the changed Privacy Policy shall take effect from the time it is posted on this website.'
                },
                {
                    title: 'Article 10 (Contact Information)',
                    content: 'For inquiries regarding this Policy, please contact the following.\n\nSeller: Zalci Audio\nEmail: zalciapp@gmail.com\nAddress/Phone: Please refer to the "Specific Commercial Transactions" page.'
                }
            ],
        },
        contact: {
            title: 'Contact Us',
            description: 'If you have any questions or feedback, please contact us using the form below.',
            form: {
                email: 'Email Address',
                subject: 'Subject',
                subjectOptions: {
                    general: 'General Inquiry',
                    bug: 'Bug Report',
                    purchase: 'Purchase/Payment Issue',
                    request: 'Feature Request',
                    other: 'Other',
                },
                otherDetail: 'Please specify briefly',
                message: 'Message Details',
                submit: 'Send Message',
                sending: 'Sending...',
                success: 'Message received. We will get back to you shortly.',
                error: 'Failed to send message. Please try again later.',
                required: 'Required',
            }
        },
        myPage: {
            title: 'My Page',
            accountSettings: 'Account Settings',
            email: 'Email Address',
            logout: 'Sign Out',
            deleteAccount: 'Delete Account',
            deleteConfirmTitle: 'Delete Account',
            deleteConfirmDescription: 'Are you sure you want to delete your account? This action cannot be undone.',
            deleteConfirmButton: 'Delete Account',
            cancel: 'Cancel',
            deleteSuccess: 'Account deleted successfully.',
            deleteError: 'Failed to delete account.',
            changePassword: 'Change Password',
            passwordResetEmailSent: 'Password reset link sent to your email.',
            passwordResetError: 'Failed to send password reset email.',
            rateLimitError: 'For security purposes, please wait a moment before trying again.',
        },
        legal: {
            title: 'Specific Commercial Transactions',
            distributor: {
                title: 'Distributor',
                content: 'Zalci Audio (Representative name will be disclosed without delay upon request)',
            },
            manager: {
                title: 'Operation Manager',
                content: 'Will be disclosed without delay upon request',
            },
            address: {
                title: 'Address',
                content: 'Address will be disclosed without delay upon request.',
                requestButton: 'Request Disclosure of Address/Name',
            },
            phone: {
                title: 'Phone Number',
                content: '080-6183-3443 (Reception hours: Weekdays 10:00-18:00)',
                note: '*Inquiries are generally accepted via email or the contact form.',
            },
            email: {
                title: 'Email Address',
                content: 'zalciapp@gmail.com',
            },
            price: {
                title: 'Selling Price',
                content: 'Amount listed on each product page (tax included)',
            },
            otherFees: {
                title: 'Fees Other Than Product Price',
                content: 'None (*Internet connection fees, communication fees, and bank transfer fees are borne by the customer)',
            },
            paymentMethod: {
                title: 'Payment Method',
                content: 'Credit Card Payment (Stripe)',
            },
            paymentTiming: {
                title: 'Payment Timing',
                content: 'At the time of product purchase (immediate settlement)',
            },
            deliveryTiming: {
                title: 'Delivery Timing',
                content: 'Successfully downloadable from the library or download link immediately after payment completion.',
            },
            returns: {
                title: 'Returns and Cancellations',
                intro: 'Based on Stripe regulations, we stipulate the following.',
                customerConvenience: {
                    title: '<Returns/Exchanges due to Customer Convenience (Non-defective products)>',
                    content: 'Due to the nature of digital content products, delivery is considered complete upon notification of the download URL (or reflection on My Page). Therefore, cancellations, returns, refunds, or exchanges due to customer convenience after payment completion are generally not accepted.\n(e.g., Returns due to reasons such as "It was different from what I thought" or "I bought it by mistake" are not accepted)',
                },
                defective: {
                    title: '<Returns/Exchanges in case of Product Defects (Defective products)>',
                    content: 'We will respond only if defects (flaws) such as corruption, unplayability, or content discrepancies are found in the downloaded file.\nIf a defect is confirmed, please contact us at the email address above within 7 days of purchase. After confirmation, we will redistribute (exchange) a normal file. Please note that due to the nature of the product, we will respond by exchanging it for a non-defective product instead of a refund.',
                },
            },
        }
    },
    ja: {
        hero: {
            title: 'クリエイターのための\n最高級AIオーディオアセット',
            description: '高度なAIによって生成されたクリーンで\n高品質なロイヤリティフリーのオーディオトラック。\nゲーム、動画、ストリーミングに最適です。',
            getStarted: '始める',
            browseLibrary: 'ライブラリを見る',
            twitterShare: 'Xでシェアする',
            loggedIn: 'ログイン済み',
        },
        notifications: {
            title: 'お知らせ',
            empty: '新しいお知らせはありません。',
            markRead: 'すべて既読にする',
            items: [
                {
                    id: '1',
                    date: '2026/02/10',
                    content: 'Zalci Audioへようこそ！新着のAI生成サウンドをぜひチェックしてください。'
                },
                {
                    id: '2',
                    date: '2026/02/09',
                    content: '2026年2月15日 (02:00 - 04:00 UTC) にシステムメンテナンスを実施予定です。'
                }
            ]
        },
        header: {
            title: 'Zalci Audio',
            sounds: '全サウンド',
            pricing: '料金',
            about: '概要',
            terms: '利用規約',
            privacy: 'プライバシーポリシー',
            legal: '特定商取引法',
            login: 'ログイン',
            signOut: 'ログアウト',
            getStarted: '始める',
            searchPlaceholder: '楽曲を検索...',
            myLibrary: 'マイライブラリ',
            library: 'ライブラリ',
            myPage: 'マイページ',
        },
        featured: {
            title: '注目トラック',
            description: '最新のAI生成傑作をご覧ください。\nあなたの次のプロジェクトのための高品質なオーディオトラックです。',
        },
        empty: '現在利用可能な楽曲はありません。',
        card: {
            buyNow: '購入する',
            processing: '処理中...',
            error: 'エラーが発生しました。もう一度お試しください。',
            inLibrary: '保有済み',
            free: '無料',
            freeDownload: '無料ダウンロード',
        },
        sounds: {
            title: '全サウンド一覧',
            description: '高品質なオーディオアセットの全コレクションをご覧ください。',
            empty: 'まだ楽曲がありません。',
            failed: '曲の読み込みに失敗しました。後でもう一度お試しください。',
            sort: {
                label: '並び替え',
                latest: '新着順',
                oldest: '古い順',
                priceHigh: '価格が高い順',
                priceLow: '価格が安い順',
                nameAsc: '名前順 (A → Z)',
                nameDesc: '名前順 (Z → A)',
            }
        },
        library: {
            title: 'マイライブラリ',
            description: '購入したサウンドの管理とダウンロードができます。',
            signInTitle: 'ライブラリを表示するにはサインイン',
            signInDesc: '購入したコンテンツにアクセスするにはログインが必要です。',
            signInButton: 'サインイン / 新規登録',
            emptyTitle: 'ライブラリは空です',
            emptyDesc: "まだサウンドを購入していません。コレクションを見て、プロジェクトに最適なオーディオを見つけましょう。",
            browseButton: 'サウンドを探す',
            purchasedPrefix: '購入日:',
        },
        about: {
            title: '概要',
            tagline: '「生成AIの力を、すべてのクリエイターに。」 ハイスペックPCも、複雑なプロンプトも必要ありません。',
            conceptTitle: 'Zalci Audioについて',
            conceptDesc: '「高性能な生成AIを使ってみたいけれど、PCのスペックが足りない…」 「自分で納得のいくまで生成を繰り返すのは、正直めんどくさい。」\n\nZalci Audioは、そんなクリエイターの皆様の代わりに、私たちが最新のAI技術を駆使して「これだ」と思える音を厳選し、提供するストアです。\n\nあなたがやることは、ライブラリからお気に入りの音を見つけ、ダウンロードするだけ。 制作の「面倒な部分」は私たちに任せて、あなたはクリエイティブな作業に集中してください。',
            roadmapTitle: '現在のラインナップと今後の展開',
            roadmapDesc: '現在、当ストアでは取り扱いやすく軽量なmp3形式を中心に素材を提供しています。 しかし、Zalci Audioはここで止まりません。今後、クリエイターの皆様のより高度なニーズにお応えするため、以下のアップデートを予定しています。\n\n・高音質WAV形式の追加（プロ仕様の制作に）\n・シームレスなループ処理済み素材（ゲーム実装をよりスムーズに）\n・MIDIデータの販売（メロディを自由にカスタマイズしたい方へ）\n\n成長し続けるライブラリとして、あなたのプロジェクトをサポートします。',
            messageTitle: '現役ゲーム開発者の視点から',
            messageDesc: 'ゲーム開発（Unity/C++）を学ぶ学生として、自分自身が「今、欲しかった音」を形にしています。AIの可能性を最大限に引き出し、開発者がストレスなく使える素材屋を目指しています。',
        },
        purchaseModal: {
            preview: 'プレビュー (20秒サンプル)',
            playSample: 'サンプル再生',
            pause: '一時停止',
            purchaseOptions: '購入オプション',
            totalAmount: '合計金額',
            payWithStripe: 'Stripeで支払う',
            purchaseWithFree: '無料ダウンロード',
            processing: '処理中...',
            securedBy: 'Stripeによる安全な決済',
            options: {
                wav: 'WAV形式 (高音質)',
                loop: 'ループバージョンを含む',
                highRes: 'ハイレゾ音源 (96kHz/24bit)',
                midi: 'MIDIデータ',
            }
        },
        login: {
            signInTitle: 'サインイン',
            signUpTitle: 'アカウント作成',
            emailLabel: 'メールアドレス',
            passwordLabel: 'パスワード',
            submitButton: 'ログイン',
            submitButtonSignUp: 'アカウント作成',
            loading: '処理中...',
            forgotPassword: 'パスワードをお忘れですか？',
            noAccount: 'アカウントをお持ちでないですか？',
            hasAccount: 'すでにアカウントをお持ちですか？',
            signUpLink: 'アカウント作成',
            loginLink: 'ログイン',
            welcome: '',
            welcomeDesc: 'アカウントにアクセスするには情報を入力してください',
            createAccount: 'はじめまして',
            createAccountDesc: '新しいアカウントを作成するには情報を入力してください',
            backToHome: 'ホームに戻る',
            newsletterLabel: 'メールマガジンの配信を希望する',
            signUpSuccess: 'はじめまして。ユーザー登録が完了しました。そのままログインしてご利用いただけます。',
            inputComplete: '入力が完了しました。',
            errors: {
                invalidCredentials: 'メールアドレスまたはパスワードが正しくありません。',
                userExists: 'このメールアドレスは既に登録されています。',
                weakPassword: 'パスワードは6文字以上で入力してください。',
                unknown: '予期せぬエラーが発生しました。',
            },
            continueWith: 'または',
            google: 'Google',
            twitter: 'X',
        },
        forgotPassword: {
            title: 'パスワードのリセット',
            description: 'メールアドレスを入力してください。リセット用リンクを送信します。',
            emailLabel: 'メールアドレス',
            submitButton: 'リセットリンクを送信',
            backToLogin: 'ログイン画面に戻る',
            successTitle: 'メールを確認してください',
            successDesc: 'アカウントが存在する場合、パスワードリセット用リンクを送信しました。',
            loading: '送信中...',
            errors: {
                invalidEmail: '有効なメールアドレスを入力してください。',
                userNotFound: 'アカウントが存在する場合、リンクを送信しました。',
                rateLimit: 'リクエストが多すぎます。しばらく時間をおいてお試しください。',
                unknown: 'エラーが発生しました。もう一度お試しください。',
            }
        },
        updatePassword: {
            title: 'パスワードの更新',
            description: '新しいパスワードを入力してください。',
            passwordLabel: '新しいパスワード',
            confirmPasswordLabel: '新しいパスワード（確認）',
            submitButton: 'パスワードを更新',
            successTitle: '更新完了',
            successDesc: 'パスワードが正常に変更されました。',
            matchError: 'パスワードが一致しません。',
            loading: '更新中...',
            errors: {
                weakPassword: 'パスワードは6文字以上で入力してください。',
                sessionExpired: 'セッションの期限が切れました。再度リセットリンクをリクエストしてください。',
                unknown: 'エラーが発生しました。もう一度お試しください。',
            }
        },
        terms: {
            title: '利用規約',
            sections: [
                {
                    title: '第1条（適用）',
                    content: '本利用規約（以下「本規約」といいます）は、Zalci Audio（以下「当サイト」といいます）が提供するオーディオ素材販売サービス（以下「本サービス」といいます）の利用条件を定めるものです。ユーザーは、本サービスの利用をもって本規約のすべての条項に同意したものとみなします。'
                },
                {
                    title: '第2条（使用許諾および権利の帰属）',
                    content: '権利の帰属: 本サービスで販売・配布される全てのオーディオ素材（以下「素材」といいます）の著作権および著作者人格権は、当サイトまたは当サイトに素材を提供したクリエイターに帰属します。本規約は、ユーザーに対して素材の著作権を譲渡するものではありません。\n\n許諾範囲: 当サイトはユーザーに対し、以下の条件に基づく非独占的かつ再許諾不可能な使用権を許諾します。\n\n用途: ゲーム、動画、配信、アプリケーション、ウェブサイト等のデジタルコンテンツ、および映像作品等の制作物（以下「成果物」といいます）への組み込み。商用・非商用を問いません。\n\n加工: ユーザーは、成果物の制作に必要な範囲で、素材のトリミング、ループ処理、音質調整等の改変を行うことができます。\n\nクレジット表記: 成果物へのクレジット表記（例：「Sound: Zalci Audio」等）は任意としますが、表記を推奨します。'
                },
                {
                    title: '第3条（禁止事項）',
                    content: 'ユーザーは、本サービスの利用にあたり、以下の行為を行ってはなりません。\n\n再配布・転売: 素材そのもの、または素材に軽微な加工を加えただけのものを、独立したファイルとして第三者に再配布、転売、貸与、譲渡する行為（BGM集としての販売、素材販売サイトへの登録等を含みます）。\n\n著作権管理システムへの登録: 素材、または素材を使用した成果物を、YouTube Content ID、JASRAC等の著作権管理団体、またはこれらに類する著作権管理システム・データベースに登録する行為。\n\nAI学習への利用: 素材を生成系AI（人工知能）の学習用データとして利用する行為、および素材を利用して生成系AIにより類似の音声を意図的に生成する行為。\n\n不正利用: 公序良俗に反する目的、犯罪行為、反社会的勢力に関連する活動、または他者の権利を侵害する目的で素材を利用する行為。\n\nアカウントの共有: 1つのアカウントを複数人で共有する行為、またはアカウント情報を第三者に譲渡・貸与する行為。'
                },
                {
                    title: '第4条（返品・キャンセル・再ダウンロード）',
                    content: '返品不可: デジタルコンテンツという商品の性質上、購入手続き完了後のキャンセル、返品、返金は原則としてお受けできません。\n\n欠陥時の対応: ダウンロードされたファイルに破損等の技術的な欠陥が認められた場合に限り、当サイトの判断により、良品との交換または再ダウンロードの措置を講じます。ただし、ユーザーの利用環境（ソフトウェア、ハードウェアの非互換性等）に起因する不具合については対象外とします。'
                },
                {
                    title: '第5条（免責事項）',
                    content: '非保証: 当サイトは、素材の完全性、正確性、特定の目的への適合性、および第三者の権利侵害の有無について、明示または黙示を問わず何ら保証しません。\n\n損害の免責: 本サービスの利用、または利用不能によりユーザーに生じたあらゆる損害（データの消失、業務の中断、逸失利益、精神的苦痛等を含みますがこれらに限定されません）について、当サイトは一切の責任を負いません。\n\nトラブルの解決: ユーザーが本サービスを利用したことにより第三者との間で生じた紛争（著作権侵害の申立て等を含みます）については、ユーザーの責任と費用において解決するものとし、当サイトは関与しません。'
                },
                {
                    title: '第6条（規約の変更）',
                    content: '当サイトは、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。変更後の規約は、当サイト上に掲示した時点で効力を生じるものとし、以降の利用については変更後の規約が適用されます。'
                },
                {
                    title: '第7条（通知および連絡）',
                    content: 'デジタルファースト: 本サービスに関する当サイトからユーザーへの通知、およびユーザーから当サイトへの連絡は、原則として電子メール、または当サイト内の問い合わせフォームを通じて行うものとします。\n\n郵送物の受領: 当サイトの運営体制およびセキュリティ保持の観点から、事前の承諾なく送付された書面（郵便物、宅配便等）について、当サイトは受領の義務を負わず、これによってユーザーに生じた不利益について一切の責任を負いません。'
                },
                {
                    title: '第8条（準拠法・裁判管轄）',
                    content: '準拠法: 本規約の解釈にあたっては、日本法を準拠法とします。\n\n管轄裁判所: 本サービスに関して紛争が生じた場合には、当サイト運営者の所在地を管轄する地方裁判所を第一審の専属的合意管轄裁判所とします。'
                }
            ]
        },
        policy: {
            title: 'プライバシーポリシー',
            intro: 'Zalci Audio（以下「当サイト」といいます）は、当サイトが提供するサービス（以下「本サービス」といいます）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下「本ポリシー」といいます）を定めます。',
            sections: [
                {
                    title: '第1条（個人情報）',
                    content: '「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報、および容貌、指紋、声紋にかかるデータ、および健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別符号）を指します。'
                },
                {
                    title: '第2条（個人情報の収集方法）',
                    content: '当サイトは、ユーザーが本サービスを利用する際に、以下の情報を収集する場合があります。\n\nユーザー提供情報: 氏名、メールアドレス、住所、電話番号、その他アカウント登録および決済時に必要な情報。\n\n決済情報: クレジットカード情報、銀行口座情報（※クレジットカード情報は決済代行会社が管理し、当サイトでは非保持化されています）。\n\n自動取得情報: IPアドレス、Cookie（クッキー）、アクセスログ、利用環境（ブラウザ、OS等）、滞在時間等のアクセス解析データ。'
                },
                {
                    title: '第3条（情報の管理とセキュリティ）',
                    content: 'パスワードの保護: 当サイトは、ユーザーが作成したアカウントのメールアドレスおよびパスワードを収集・保持します。パスワードについては、適切なハッシュ化アルゴリズム（ソルト付与等）を用いて暗号化した状態で保存し、当サイト運営者であっても元のパスワードを閲覧・復元できない仕組みを導入し、厳重に管理いたします。\n\n安全管理措置: 当サイトは、個人情報の漏洩、滅失または毀損の防止その他の個人情報の安全管理のために、SSL（Secure Sockets Layer）による通信の暗号化や、不正アクセス防止のための技術的対策を講じます。\n\nユーザーの責任: ユーザーは、自己のパスワードを第三者に知られないよう、適切に管理する責任を負うものとします。パスワードの推測が容易な文字列の使用や、他サイトとの使い回しを避けることを強く推奨します。'
                },
                {
                    title: '第4条（個人情報の利用目的）',
                    content: '当サイトが個人情報を収集・利用する目的は、以下のとおりです。\n\n本サービスの提供・運営のため（ダウンロードリンクの送付、マイページ機能の提供等）。\n\nユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）。\n\n有料サービスにおいて、利用料金を請求するため。\n\nメンテナンス、重要なお知らせなど必要に応じたご連絡のため。\n\n利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの特定をし、ご利用をお断りするため。\n\n上記の利用目的に付随する目的。'
                },
                {
                    title: '第5条（個人情報の第三者提供）',
                    content: '当サイトは、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。\n\n人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき。\n\n公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき。\n\n国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき。'
                },
                {
                    title: '第6条（外部委託および決済代行）',
                    content: '当サイトは、本サービスの運営に必要な範囲で、個人情報の取扱いの一部を外部（決済代行会社、サーバー管理会社等）に委託する場合があります。この場合、当サイトは当該委託先との間で機密保持契約を締結する等の適切な監督を行います。\n\nクレジットカード決済: 本サービスのクレジットカード決済には、Stripe, Inc.（Stripe Japan株式会社）の決済サービスを利用しています。ユーザーのクレジットカード情報はStripeのサーバーに直接送信され、当サイトのサーバー・データベース内には一切保存されません。'
                },
                {
                    title: '第7条（アクセス解析ツールについて）',
                    content: '当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を利用しています。このGoogleアナリティクスはトラフィックデータの収集のためにCookieを使用しています。このトラフィックデータは匿名で収集されており、個人を特定するものではありません。この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。'
                },
                {
                    title: '第8条（個人情報の開示・訂正・利用停止等）',
                    content: 'ユーザーから個人情報の開示、訂正、追加、削除、利用停止、消去（以下「開示等」といいます）を求められたときは、ご本人であることを確認させていただいた上で、遅滞なく対応いたします。ただし、個人情報保護法その他の法令により、当サイトが開示等の義務を負わない場合は、この限りではありません。'
                },
                {
                    title: '第9条（プライバシーポリシーの変更）',
                    content: '本ポリシーの内容は、法令その他本ポリシーに別段の定めのある事項を除いて、ユーザーに通知することなく変更することができるものとします。当サイトが別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとする。'
                },
                {
                    title: '第10条（お問い合わせ窓口）',
                    content: '本ポリシーに関するお問い合わせは、下記の窓口までお願いいたします。\n\n販売業者: Zalci Audio\nメールアドレス: zalciapp@gmail.com\n住所・電話番号: 「特定商取引法に基づく表記」ページをご参照ください。'
                }
            ]
        },
        contact: {
            title: 'お問い合わせ',
            description: 'ご質問やフィードバック等がございましたら、以下のフォームよりお気軽にお問い合わせください。',
            form: {
                email: 'メールアドレス',
                subject: 'お問い合わせ内容',
                subjectOptions: {
                    general: '一般的なご質問',
                    bug: '不具合の報告',
                    purchase: '購入・決済について',
                    request: '機能リクエスト',
                    other: 'その他',
                },
                otherDetail: '内容を簡潔にご記入ください',
                message: '詳細内容',
                submit: '送信する',
                sending: '送信中...',
                success: 'お問い合わせを受け付けました。返信まで今しばらくお待ちください。',
                error: '送信に失敗しました。時間をおいて再度お試しください。',
                required: '必須項目です',
            }
        },
        myPage: {
            title: 'マイページ',
            accountSettings: 'アカウント設定',
            email: 'メールアドレス',
            logout: 'ログアウト',
            deleteAccount: 'アカウント削除',
            deleteConfirmTitle: 'アカウント削除',
            deleteConfirmDescription: '本当にアカウントを削除しますか？この操作は取り消せません。',
            deleteConfirmButton: '削除する',
            cancel: 'キャンセル',
            deleteSuccess: 'アカウントを削除しました。',
            deleteError: 'アカウントの削除に失敗しました。',
            changePassword: 'パスワードの変更',
            passwordResetEmailSent: 'パスワードリセット用のリンクをメールに送信しました。',
            passwordResetError: 'メールの送信に失敗しました。',
            rateLimitError: 'セキュリティのため、しばらく時間をおいてから再試行してください。',
        },
        legal: {
            title: '特定商取引法に基づく表記',
            distributor: {
                title: '販売業者',
                content: 'Zalci Audio （代表者氏名については、請求があった場合に遅滞なく開示いたします）',
            },
            manager: {
                title: '運営責任者',
                content: '請求があった場合に遅滞なく開示いたします',
            },
            address: {
                title: '住所',
                content: '請求があった場合に遅滞なく開示いたします。',
                requestButton: '【住所・氏名の開示を請求する】',
            },
            phone: {
                title: '電話番号',
                content: '080-6183-3443 （受付時間：平日10:00〜18:00）',
                note: '※お問い合わせは原則としてメールまたはフォームよりお願いいたします。',
            },
            email: {
                title: 'メールアドレス',
                content: 'zalciapp@gmail.com',
            },
            price: {
                title: '販売価格',
                content: '各商品ページに記載の金額（消費税込み）',
            },
            otherFees: {
                title: '商品代金以外の必要料金',
                content: 'なし （※インターネット接続料金、通信料金、および銀行振込時の振込手数料等は、お客様のご負担となります）',
            },
            paymentMethod: {
                title: 'お支払い方法',
                content: 'クレジットカード決済（Stripe）',
            },
            paymentTiming: {
                title: '代金の支払時期',
                content: '商品購入時（即時決済となります）',
            },
            deliveryTiming: {
                title: '商品の引渡時期',
                content: '決済完了後、ライブラリまたはダウンロードリンクより即時ダウンロードいただけます。',
            },
            returns: {
                title: '返品・キャンセルについて',
                intro: '当ショップの規定に基づき、以下の通り定めます。',
                customerConvenience: {
                    title: '＜お客様都合による返品・交換（良品の場合）＞',
                    content: 'デジタルコンテンツという商品の性質上、ダウンロード用URLの通知（またはマイページへの反映）をもって納品完了とみなします。そのため、決済完了後のお客様都合によるキャンセル・返品・返金・交換には原則として応じられません。\n（例：「思っていた音と違った」「間違えて購入した」等の理由による返品は不可となります）',
                },
                defective: {
                    title: '＜商品に不備がある場合の返品・交換（不良品の場合）＞',
                    content: 'ダウンロードしたファイルに破損、再生不可、内容の相違等の不備（瑕疵）が認められた場合に限り、対応いたします。\n不備が確認された場合、購入後7日以内に上記メールアドレスまでご連絡ください。弊社にて確認の上、正常なファイルの再配布（交換）を行わせていただきます。商品の性質上、返金ではなく良品との交換での対応となりますことをご了承ください。',
                },
            },
        }
    }
}
