import { headers, cookies } from 'next/headers'

export type Locale = 'en' | 'ja'

export const dictionaries = {
    en: {
        hero: {
            title: 'Premier AI Audio Assets for Creators',
            description: 'High-quality, royalty-free audio tracks generated by advanced AI. Perfect for games, videos, and streaming.',
            getStarted: 'Get Started',
            browseLibrary: 'Browse Library',
            twitterFollow: 'Follow along on Twitter',
        },
        header: {
            title: 'Zalci Audio',
            sounds: 'Sounds',
            pricing: 'Pricing',
            about: 'About',
            login: 'Login',
            signOut: 'Sign Out',
            getStarted: 'Get Started',
        },
        featured: {
            title: 'Featured Tracks',
            description: 'Discover our latest AI-generated masterpieces. High-quality audio tracks ready for your next project.',
        },
        empty: 'No songs available at the moment.',
        card: {
            buyNow: 'Buy Now',
            processing: 'Processing...',
            error: 'Something went wrong. Please try again.',
        },
    },
    ja: {
        hero: {
            title: 'クリエイターのための最高級AIオーディオ資産',
            description: '高度なAIによって生成された高品質でロイヤリティフリーのオーディオトラック。ゲーム、動画、ストリーミングに最適です。',
            getStarted: '始める',
            browseLibrary: 'ライブラリを見る',
            twitterFollow: 'Twitterでフォローする',
        },
        header: {
            title: 'Zalci Audio',
            sounds: 'サウンド',
            pricing: '料金',
            about: '概要',
            login: 'ログイン',
            signOut: 'ログアウト',
            getStarted: '始める',
        },
        featured: {
            title: '注目トラック',
            description: '最新のAI生成傑作をご覧ください。あなたの次のプロジェクトのための高品質なオーディオトラックです。',
        },
        empty: '現在利用可能な楽曲はありません。',
        card: {
            buyNow: '購入する',
            processing: '処理中...',
            error: 'エラーが発生しました。もう一度お試しください。',
        },
    },
}

export async function getDictionary() {
    const cookieStore = await cookies()
    const localeCookie = cookieStore.get('NEXT_LOCALE')

    if (localeCookie?.value === 'ja' || localeCookie?.value === 'en') {
        return dictionaries[localeCookie.value as Locale]
    }

    const headersList = await headers()
    const acceptLanguage = headersList.get('accept-language') || 'en'
    const locale: Locale = acceptLanguage.startsWith('ja') ? 'ja' : 'en'
    return dictionaries[locale] // Return plain object, not a promise
}
