import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { ArrowRight } from 'lucide-react'

export function Hero() {
    return (
        <section className="space-y-6 pb-8 pt-6 md:pb-12 md:pt-10 lg:py-32">
            <div className="container flex max-w-[64rem] flex-col items-center gap-4 text-center">
                <Link
                    href="/twitter"
                    className="rounded-2xl bg-muted px-4 py-1.5 text-sm font-medium"
                    target="_blank"
                >
                    Follow along on Twitter
                </Link>
                <h1 className="font-heading text-3xl sm:text-5xl md:text-6xl lg:text-7xl font-bold">
                    Premier AI Audio Assets for Creators
                </h1>
                <p className="max-w-[42rem] leading-normal text-muted-foreground sm:text-xl sm:leading-8">
                    High-quality, royalty-free audio tracks generated by advanced AI.
                    Perfect for games, videos, and streaming.
                </p>
                <div className="space-x-4">
                    <Link href="/login">
                        <Button size="lg" className="h-11 px-8 gap-2">
                            Get Started <ArrowRight className="h-4 w-4" />
                        </Button>
                    </Link>
                    <Link href="/products">
                        <Button variant="outline" size="lg" className="h-11 px-8">
                            Browse Library
                        </Button>
                    </Link>
                </div>
            </div>
        </section>
    )
}
